### PR TITLE
optimizer: build date histograms with timeField

### PR DESCRIPTION
**Pull request by davidvgalbraith**
The date histogram builder assumes that the time field is always 'time'.
That's not right. It should use the timeField parameter.

This defeated our tests because we always write points with a "time" field
as well as the timeField, so date histograms on the "time" field work
even though it's not the timeField. Let's drop the "time" field from points
with a timeField on write.

fixes https://github.com/juttle/juttle-elastic-adapter/issues/66

@demmer @VladVega @dmehra

### CODE REVIEW

**Comment by VladVega** [comment]
I think maybe a warning should be thrown if there is content in the `time` field overwritten by the value in `pt[timeField]`.

**Comment by VladVega** [comment]
Otherwise looks good +1. 

Related but not exactly question: `read elastic -timeField "my_time"` will set the time field as well without any aggregation?

**Comment by davidvgalbraith** [comment]
Points coming into `write elastic` always have a `time` field, since they come from the Juttle runtime. `write` puts the value of that field into the `timeField` field for storage. So warning doesn't make sense.

`read elastic` takes points out of storage that have times in the `timeField` field, and it puts those times into the `time` field. It works with or without optimization.

**Comment by davidvgalbraith** [comment]
But the opposite makes perfect sense! If the points have a `timeField` field that we're clobbering with the value of the `time` field, we should warn. I suppose that's what you meant.

**Pull request merged**
