### PR TITLE
add coverage checking

### PR DESCRIPTION
**Pull request by rlgomes**
lets add coverage checking for the elastic-adapter

### CODE REVIEW

**Comment by rlgomes** [comment]
@davidvgalbraith @juttle/developers

**Comment by rlgomes** [comment]
We need to add this type of check to all the adapters so we can easily identify which areas need more testing coverage. In this case after running this there's a report at `juttle-elastic-adapter/coverage/lcov-report/lib/index.html` which highlights that the `filter-es-compiler.js` needs a lot more testing:

**Comment by dmehra** [comment]
+1 we should have this in all adapters. very useful for assessing what tests need to be added.
@davidvgalbraith i'm also reading through the existing tests, as they didn't get reviewed when going through PR.

**Comment by rlgomes** [comment]
@davidvgalbraith shall we merge this ?

**Comment by davidvgalbraith** [comment]
+1

**Pull request merged**
