### PR TITLE
Support non-day index intervals

### LINKED ISSUE #25: "logstash schema"
What is the "logstash schema"? More specifically, what are the requirements for an ES "schema" to be juttle-readable?

I have a set of events that I'm storing in ES. I'd be interested to use Juttle on it, but I don't know how I need to structure the documents in order for this adapter to be able to use them.

### PR DESCRIPTION
**Pull request by davidvgalbraith**
resolves #25 

Now you can read and write from weekly, monthly, yearly,
or singular indices by specifying -index_interval in
read commands or configuration.

@demmer @VladVega @go-oleg @rlgomes @dmehra

### CODE REVIEW

**Comment by dmehra** [comment]
please update the README with new options and expected behavior.
this is still using @timestamp field for time, right?

**Comment by henridf** [comment]
working for me. looking forward to support for configurable timefield!

**Comment by davidvgalbraith** [comment]
I put README changes for `index_prefix`, `index_interval`, and the still-in-progress `time_field` all on this branch.

**Comment by demmer** [comment]
See comment on #25 with an alternative suggestion for how we could get the same functionality in a way that (IMO) would be easier to reason about and more flexible.

**Comment by davidvgalbraith** [comment]
Updated the code for yesterday's suggestions. README changes still in the works.

**Comment by davidvgalbraith** [comment]
README updates complete.

**Comment by dmehra** [comment]
Did I correctly interpret that with `indexInterval` defaulting to 'none', the Logstash schema is no longer the default one? So if I use logstash for ingest, I will be required to pass indexInterval='day' to able to read the data? Since logstash is common, maybe this deserves a subsection.

**Comment by davidvgalbraith** [comment]
You correctly interpreted! Check the new README as I do describe how to read from Logstash in the new world.

**Comment by davidvgalbraith** [comment]
Technically you don't need to specify `-indexInterval day` to read from Logstash as long as you do `-index logstash-*`. It's more robust against big data with `-indexInterval day` though.

**Comment by davidvgalbraith** [comment]
And since the default read index is `*` you don't even have to do `-index logstash-*` as long as Logstash is the only data in your Elasticsearch.

**Comment by dmehra** [comment]
My observation is that we are changing the default. Previously `read elastic` "just worked" for logstash schema, with no options. Now one must specify `read elastic -index 'logstash-*'` at a minimum, or (as documented) `read elastic -index 'logstash-*' -indexInterval 'none'`. I'll update the very-much-in-flux demo to account for this. The README is sufficient, but examples would be handy here. Maybe we can just link to the demos once they are in.

**Comment by demmer** [comment]
@dmehra As @davidvgalbraith pointed out in his last comment, while it is true that we're changing the default, it's also true that `read elastic` will still "just work" assuming you only have logstash data in your ES instance.

**Comment by dmehra** [comment]
Now that I see that comment (caching...) it seems handy, but not documented and therefore magical. Can we have a README section specifically for the handling of Logstash schema, since it is common?

**Comment by davidvgalbraith** [comment]
I made a section.

**Comment by dmehra** [comment]
+1 on the README, nice

**Comment by demmer** [comment]
Looks good to me!

**Pull request merged**
